# Read HDF files from results database
This notebook shows how to read, visualize and process openmc results. In addition, it shows how to store them in an HDF file for the `\results_database\` folder of a given benchmark. To do that we will take advantage of the `\example results\` and `\example_database\` folders. In the former we stored an example openmc `statepoint` file (`example_statepoint.100.h5`) to read. In the latter we will store our new `my_openmc_results.h5` file with the results rearranged consistently with the other HDF files already present in the `\results_database\` folders.

In [1]:
import openmc_fusion_benchmarks as ofb
import numpy as np

Read openmc `statepoint` file:

In [2]:
openmc_results = ofb.ResultsFromOpenmc(file='example_results/example_statepoint.100.h5')

Unfortunately we need a bit of postoprocessing before storing them in a new HDF file. Most likely we need to divide the tally by the geometry filter dimensions (e.g. surface area, cell volume, mesh element volume etc.) but other steps might be necessary, depending on the tally. Here we have the volume of the cells.

In [3]:
_foil_volume = .1 * 1.8**2/4 * np.pi
volumes_onaxis1 = np.concatenate((np.ones(5), np.ones(4)*2, np.ones(4)*3)) * _foil_volume

openmc_results.get_tally_dataframe(tally_name='rr_onaxis1_nb93', normalize_over=None)

    cell particle  energyfunction nuclide score     mean  std. dev.
0    135  neutron  c0eb4a8954a405   total  flux 3.11e-04   4.16e-08
1    158  neutron  c0eb4a8954a405   total  flux 3.57e-05   1.39e-08
2    181  neutron  c0eb4a8954a405   total  flux 1.27e-05   8.19e-09
3    204  neutron  c0eb4a8954a405   total  flux 6.10e-06   5.05e-09
4    602  neutron  c0eb4a8954a405   total  flux 4.71e-06   4.20e-09
5    239  neutron  c0eb4a8954a405   total  flux 6.27e-06   6.90e-09
6    262  neutron  c0eb4a8954a405   total  flux 1.85e-06   4.71e-09
7    285  neutron  c0eb4a8954a405   total  flux 5.23e-07   2.30e-09
8    308  neutron  c0eb4a8954a405   total  flux 1.45e-07   1.10e-09
9    331  neutron  c0eb4a8954a405   total  flux 6.18e-08   9.45e-10
10   363  neutron  c0eb4a8954a405   total  flux 1.73e-08   4.34e-10
11   386  neutron  c0eb4a8954a405   total  flux 5.95e-09   2.95e-10
12   398  neutron  c0eb4a8954a405   total  flux 2.53e-09   1.95e-10

I is possible to extract some useful information about the code and the simulation settings:

In [4]:
version = openmc_results.get_openmc_version
batches = openmc_results.get_batches
ppbatch = openmc_results.get_particles_per_batch

print(f'Code version: {version}')
print(f'Batches: {batches}')
print(f'Particles per batch: {ppbatch}')

Code version: (0, 13, 3)
Batches: 100
Particles per batch: 1.00e+08

## Store results in a database-compatible HDF file
It is possible to store the postprocessed tally in a HDF file compatible with the other files already present in the `\results_database\` folders of the benchmarks available in `\model\`. Of course some information need to be given:
- The name of the HDF file (either existing or to create) to store the results in
- The name of the tally (should not change from the name in the `statepoint` file or, at least, it has to be consistent with the name present in the other HDF files in the database)

Additional:
- Normalization for postprocessing (e.g. cell volume)
- Name of the nuclear data library used (strongly recommended)
- When the simulation has been run
- Where it has been run

In [5]:
xaxis_list = ['0.25', '12.95', '25.95', '38.65', '43.82', '46.35', 
              '53.3', '60.05', '66.9', '73.9', '80.6', '87.25', '91.65']
openmc_results.tally_to_hdf(tally_name='rr_onaxis1_nb93', 
                            normalize_over=volumes_onaxis1, 
                            xs_library='FENDL-3.2b', 
                            xaxis_name='Shield depth (cm)',
                            xaxis_list=xaxis_list,
                            path_to_database='example_database', 
                            when='November 2023', where='MIT-PSFC')

/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'Shield depth (cm)'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/path.py:137: NaturalNameWarning: object name is not a valid Python identifier: 'std. dev.'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'Shield depth (cm)_kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'Shield depth (cm)_meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'Shield depth (cm)_dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'std. dev._kind'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'std. dev._meta'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)
/home/segantin/miniconda3/envs/openmc_env2/lib/python3.11/site-packages/tables/attributeset.py:457: NaturalNameWarning: object name is not a valid Python identifier: 'std. dev._dtype'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  check_attribute_name(name)

Let's verify that we stored something in our file:

In [6]:
openmc_file = ofb.ResultsFromDatabase(file='example_database/openmc-0-13-3_fendl32b.h5')
openmc_file.get_tally_dataframe(tally_name='rr_onaxis1_nb93')

   Shield depth (cm)          mean     std. dev.
0               0.25  1.221892e-03  1.633125e-07
1              12.95  1.401898e-04  5.468312e-08
2              25.95  5.005037e-05  3.216624e-08
3              38.65  2.395322e-05  1.983948e-08
4              43.82  1.851027e-05  1.651716e-08
5              46.35  1.231300e-05  1.356592e-08
6               53.3  3.629120e-06  9.248214e-09
7              60.05  1.028079e-06  4.514237e-09
8               66.9  2.850572e-07  2.165849e-09
9               73.9  8.096823e-08  1.237537e-09
10              80.6  2.261815e-08  5.678813e-10
11             87.25  7.791191e-09  3.870651e-10
12             91.65  3.308972e-09  2.547918e-10

In [7]:
openmc_file.print_all_info()

Info:
 When: November 2023
 Where: MIT-PSFC
 Code version: openmc-0.13.3
 XS library: FENDL-3.2b
 Literature: n/a